spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kr_richard_dev?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: skrktnno1@#$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

token:
  expiration_time: 1800000
  secret: kr_richard_msa_secret_code_dev_alpha

gateway:
  ip: 10.77.118.33
