server:
  port: 0
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import: optional:configserver:http://127.0.0.1:8888
  cloud:
    config:
      name: kr_richard
      profile: alpha
      label: master
#====== DataBase/JPA =============
#  datasource:
#    url: jdbc:mysql://localhost:3306/kr_richard_eureka?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: skrktnno1@#$
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  sql:
#    init:
#      mode: never

#===== Eureka ====
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

#==== actuator ====
management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh, busrefresh, info, metrics, prometheus

#==== logging ====
logging:
  level:
    kr.richard.orderservice: debug

#==== Filter ====
greeting:
  message: kr.richard.order-service

#==== token ====
#token:
#  expiration_time: 18000000 #(30?)
#  secret: kr.richard.spring.cloud.msa.dev