server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:richardj78-life/kr.richard.cloud.config.git
          #          skip-ssl-validation: true
          ignore-local-ssh-settings: true
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFHTBrHgG5ABP88gSCi2uMILQfUyBlV56TwSfZP5IQcdoAoGCCqGSM49
            AwEHoUQDQgAEiphTzce1KMYJk+OEewTnaSfYIBkEn47BcGcSyhzENHBy6nSuuxdw
            /17rbztkLAJz+KVWedIHXHneKGw1O56G4A==
            -----END EC PRIVATE KEY-----
          default-label: master
  rabbitmq:
#    host: rabbitmq
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh, busrefresh


#          github ssh pu key set
#          ssh-keygen: ssh-keygen -M PEM -t ecdsa -b 256 -C "richardj78.life@gmail.com" -f keyfilename
#          host-key : ssh-keyscan -t ecdsa github.com
